services:
  api:
    build: ./api
    restart: unless-stopped
    env_file: .env

  web:
    build: ./web
    restart: unless-stopped

  proxy:
    build: ./proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web
  
  bloock:
    image: bloock/managed-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - api
      - web