services:
  web:
    build: ./web
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"

  api:
    build: ./api
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:3500:80"

  bloock:
    image: bloock/managed-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - api
      - web